name: Deploy Sync Cinema

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # 构建前端
      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          npm install
          VITE_API_URL=https://imtangx.top/api 
          VITE_WS_URL=wss://imtangx.top/ws 
          npm run build

      # 部署 shared 目录
      - name: Deploy shared
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /var/www/sync-cinema/shared
            rm -rf /var/www/sync-cinema/shared/*

      - name: Copy shared files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "shared/**"
          target: "/var/www/sync-cinema"

      # 部署前端文件
      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /var/www/sync-cinema/dist
            rm -rf /var/www/sync-cinema/dist/*

      - name: Copy frontend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "frontend/dist/*"
          target: "/var/www/sync-cinema/dist"

      # 部署后端
      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /var/www/sync-cinema/backend
            pm2 delete sync-cinema-backend || true
            rm -rf /var/www/sync-cinema/backend/*

      - name: Copy backend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "backend/*"
          target: "/var/www/sync-cinema/backend"

      # 启动后端服务
      - name: Start backend service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/sync-cinema/backend
            npm install
            pm2 start index.js --name sync-cinema-backend