name: Deploy Sync Cinema

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 添加调试步骤
      - name: Debug
        run: |
          echo "Checking if secrets exist..."
          if [ -n "${{ secrets.SERVER_HOST }}" ]; then
            echo "SERVER_HOST exists"
          else
            echo "SERVER_HOST is missing"
          fi
          if [ -n "${{ secrets.SERVER_USERNAME }}" ]; then
            echo "SERVER_USERNAME exists"
          else
            echo "SERVER_USERNAME is missing"
          fi
          if [ -n "${{ secrets.SERVER_PASSWORD }}" ]; then
            echo "SERVER_PASSWORD exists"
          else
            echo "SERVER_PASSWORD is missing"
          fi
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # 构建前端
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        env:
          VITE_API_URL: https://imtangx.top/api
          VITE_WS_URL: wss://imtangx.top/ws
        run: npm run build

      # 测试 SSH 连接
      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          debug: true
          script: |
            echo "Testing connection"
            pwd
            whoami
      # 清理并部署前端文件
      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /var/www/sync-cinema/dist
            rm -rf /var/www/sync-cinema/dist/*
      - name: Copy frontend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "frontend/dist/*"
          target: "/var/www/sync-cinema/dist"
          strip_components: 2

      - name: Deploy shared
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /var/www/sync-cinema/shared
            rm -rf /var/www/sync-cinema/shared/*

      - name: Copy shared files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "shared/*"
          target: "/var/www/sync-cinema/shared"
          strip_components: 1
      
      # 安装 shared 依赖
      - name: Install shared dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/sync-cinema/shared
            npm install

      # 部署后端
      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /var/www/sync-cinema/backend
            pm2 stop sync-cinema-backend || true
            rm -rf /var/www/sync-cinema/backend/*
      - name: Copy backend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "backend/*"
          target: "/var/www/sync-cinema/backend"
          strip_components: 1

      # 重启后端服务
      - name: Start backend service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/sync-cinema/backend
            npm ci
            pm2 restart sync-cinema-backend || pm2 start index.js --name sync-cinema-backend